-- =====================================================
-- AUTO-GENERATED INSERT STATEMENTS (100 ROWS PER TABLE)
-- =====================================================

TRUNCATE TABLE GATE, TERMINAL, FLIGHT, ROUTE, AIRCRAFT, AIRPORT RESTART IDENTITY CASCADE;

-- Table: AIRPORT
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('New Kimberlyshire International Airport', 'North Steven', 'Wisconsin', 'Finland', 'OTJ', 'UTC+10');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('Jillbury International Airport', 'West Lindseyhaven', 'Rhode Island', 'United States Minor Outlying Islands', 'AOX', 'UTC-4');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('Petersburgh International Airport', 'South Kimberly', 'South Dakota', 'Bolivia', 'MOX', 'UTC-5');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('South Calvinville International Airport', 'New Kevinbury', 'Delaware', 'Bouvet Island (Bouvetoya)', 'SJP', 'UTC-11');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('East Laura International Airport', 'Donnashire', 'Tennessee', 'Sweden', 'LBB', 'UTC+3');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('Justinhaven International Airport', 'Lake Jaimeton', 'California', 'India', 'TAZ', 'UTC+10');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('New Richard International Airport', 'Henryside', 'Wyoming', 'Lebanon', 'YGE', 'UTC-7');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('Port Michael International Airport', 'Janetmouth', 'California', 'Bosnia and Herzegovina', 'AXU', 'UTC+8');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('Elizabethview International Airport', 'Burchmouth', 'Kentucky', 'Libyan Arab Jamahiriya', 'NWD', 'UTC+8');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('Lake Scott International Airport', 'Madisonview', 'Alaska', 'San Marino', 'EBI', 'UTC+10');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('Cherylview International Airport', 'Whiteton', 'Colorado', 'Belarus', 'MWK', 'UTC-12');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('South Cynthiaberg International Airport', 'Torresmouth', 'California', 'Martinique', 'OEK', 'UTC-1');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('New Corymouth International Airport', 'Josephbury', 'South Dakota', 'Lao People''s Democratic Republic', 'ZTX', 'UTC-7');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('Robertsonside International Airport', 'North Arielchester', 'Mississippi', 'Saint Barthelemy', 'GLO', 'UTC-12');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('East Tinamouth International Airport', 'Lake Ashleyland', 'Colorado', 'Vietnam', 'YOY', 'UTC-4');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('East Amy International Airport', 'Danielton', 'Virginia', 'Singapore', 'BAS', 'UTC-5');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('Ashleyborough International Airport', 'South Jackchester', 'Iowa', 'Cameroon', 'BMF', 'UTC+7');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('Millerborough International Airport', 'Davisport', 'New Jersey', 'Nepal', 'APX', 'UTC-10');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('Lake Cassandrafurt International Airport', 'Norrisfurt', 'Massachusetts', 'Gibraltar', 'MLN', 'UTC-11');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('Haroldberg International Airport', 'Thomasfurt', 'Tennessee', 'Senegal', 'XJS', 'UTC-12');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('Lisaburgh International Airport', 'Cooperville', 'Florida', 'Moldova', 'EXZ', 'UTC+3');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('Cohenton International Airport', 'Port Craig', 'Nebraska', 'Iraq', 'IXG', 'UTC+8');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('Jamestown International Airport', 'East Keith', 'Connecticut', 'Rwanda', 'XYQ', 'UTC+12');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('Thomasborough International Airport', 'Hillmouth', 'Florida', 'Namibia', 'RLO', 'UTC-1');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('South Caitlin International Airport', 'Ballardburgh', 'New Mexico', 'Taiwan', 'BHD', 'UTC+12');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('South Anthony International Airport', 'Rhodesville', 'California', 'Tunisia', 'MOY', 'UTC-12');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('South Larry International Airport', 'Gordonborough', 'North Dakota', 'Mali', 'ALC', 'UTC-11');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('New Josephtown International Airport', 'South Scott', 'Idaho', 'Sierra Leone', 'OOR', 'UTC-9');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('Marymouth International Airport', 'Josefurt', 'Delaware', 'Turks and Caicos Islands', 'CKX', 'UTC+3');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('Lake Antoniofurt International Airport', 'Sanchezmouth', 'Ohio', 'Latvia', 'QQM', 'UTC+10');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('Hillstad International Airport', 'Whitakermouth', 'Colorado', 'Turks and Caicos Islands', 'WDL', 'UTC+5');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('Lewischester International Airport', 'Wardchester', 'Nevada', 'Honduras', 'NTY', 'UTC+5');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('Alexandraberg International Airport', 'North Ninatown', 'Nevada', 'Colombia', 'MQS', 'UTC-12');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('Boyleburgh International Airport', 'Batesberg', 'Oklahoma', 'French Polynesia', 'LII', 'UTC-12');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('East Barbaraborough International Airport', 'Garzastad', 'Indiana', 'Grenada', 'OYL', 'UTC-1');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('West Laurastad International Airport', 'Port Oliviachester', 'Louisiana', 'Estonia', 'ZFZ', 'UTC-4');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('Thomaston International Airport', 'West Sandra', 'Connecticut', 'Jersey', 'DSQ', 'UTC-9');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('Leroyburgh International Airport', 'Millerport', 'Montana', 'Ukraine', 'TSR', 'UTC+9');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('West Terri International Airport', 'South Joshua', 'Nebraska', 'Belize', 'STD', 'UTC+7');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('Warnertown International Airport', 'Port Leroy', 'Alaska', 'United Kingdom', 'ORO', 'UTC-1');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('Antoniofort International Airport', 'Reedtown', 'Missouri', 'Antarctica (the territory South of 60 deg S)', 'YHM', 'UTC-8');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('Chadburgh International Airport', 'Justinburgh', 'Kentucky', 'El Salvador', 'HCO', 'UTC+2');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('Dawsonhaven International Airport', 'Clairebury', 'California', 'Austria', 'NWT', 'UTC+9');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('Lake Alexandra International Airport', 'South Tanya', 'Mississippi', 'Reunion', 'AUT', 'UTC-4');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('Lauraside International Airport', 'Colleenfort', 'Hawaii', 'Sweden', 'AIN', 'UTC-4');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('Jonesside International Airport', 'Lake Gregory', 'Michigan', 'Korea', 'GEQ', 'UTC-3');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('Ericksonfurt International Airport', 'South Allisonburgh', 'Virginia', 'Zimbabwe', 'WXO', 'UTC+6');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('Johnland International Airport', 'Mooreport', 'Kentucky', 'Haiti', 'KCU', 'UTC+11');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('Calhounview International Airport', 'Lake Heatherchester', 'Wisconsin', 'Tokelau', 'BYQ', 'UTC-3');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('Markview International Airport', 'Cynthiaton', 'South Dakota', 'Guadeloupe', 'JCT', 'UTC+5');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('North Stephen International Airport', 'Lake Karen', 'New Jersey', 'Saudi Arabia', 'AMI', 'UTC-1');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('South Zacharyhaven International Airport', 'New Donaldshire', 'Missouri', 'Niue', 'QAN', 'UTC+7');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('Colemanville International Airport', 'Smithstad', 'South Carolina', 'Lao People''s Democratic Republic', 'NJS', 'UTC-1');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('New Nancy International Airport', 'Port Jessicachester', 'South Dakota', 'Monaco', 'JUW', 'UTC+8');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('Timothyburgh International Airport', 'Robersontown', 'South Dakota', 'Myanmar', 'LXG', 'UTC+7');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('New Emily International Airport', 'North Ryan', 'Colorado', 'Croatia', 'IYA', 'UTC-11');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('Shirleytown International Airport', 'South Josephberg', 'Texas', 'Poland', 'ZCV', 'UTC+1');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('Morsechester International Airport', 'East Brittneyville', 'Vermont', 'Iran', 'MLM', 'UTC-8');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('South Daniel International Airport', 'Smithmouth', 'West Virginia', 'Kiribati', 'ZHC', 'UTC+6');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('Reyesburgh International Airport', 'Fisherhaven', 'Alabama', 'Slovenia', 'BED', 'UTC+10');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('East Cathy International Airport', 'Alexfort', 'New Hampshire', 'Sri Lanka', 'APW', 'UTC-1');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('Lake Joshua International Airport', 'Bennettchester', 'Colorado', 'Martinique', 'YZM', 'UTC+3');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('Lake Brittney International Airport', 'Annastad', 'Mississippi', 'Monaco', 'PSM', 'UTC+12');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('Tracymouth International Airport', 'Caseymouth', 'South Dakota', 'Cape Verde', 'GLJ', 'UTC-6');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('New Abigailland International Airport', 'Sarafort', 'Alabama', 'Andorra', 'OYO', 'UTC-12');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('Jacobshire International Airport', 'Tracieville', 'Nevada', 'Guinea-Bissau', 'DBZ', 'UTC-2');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('Lake Jameschester International Airport', 'Jacquelinetown', 'Hawaii', 'Malaysia', 'DRK', 'UTC+8');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('Johnville International Airport', 'Vasqueztown', 'New Jersey', 'Morocco', 'RHM', 'UTC-4');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('Hillberg International Airport', 'Amberton', 'Idaho', 'Ethiopia', 'DBO', 'UTC-7');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('Harrischester International Airport', 'Heidiview', 'Nevada', 'Korea', 'LEC', 'UTC+1');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('Swansonhaven International Airport', 'Holderport', 'Virginia', 'Korea', 'TEQ', 'UTC+3');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('Maryborough International Airport', 'Barnesfurt', 'Oregon', 'Tokelau', 'KDQ', 'UTC+4');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('Peterborough International Airport', 'Brownchester', 'Hawaii', 'Netherlands', 'WFR', 'UTC-2');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('West Christinashire International Airport', 'New Hailey', 'North Dakota', 'Pitcairn Islands', 'HYX', 'UTC-11');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('North Patricia International Airport', 'Simmonsfort', 'Oregon', 'Malaysia', 'UEF', 'UTC+3');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('North Taylor International Airport', 'Smithfort', 'Massachusetts', 'Anguilla', 'QRY', 'UTC-6');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('Lake Donna International Airport', 'West Connie', 'Arkansas', 'Bosnia and Herzegovina', 'MOQ', 'UTC-3');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('South Williamshire International Airport', 'Tonyaton', 'Pennsylvania', 'Cyprus', 'QCB', 'UTC+6');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('Colemanfurt International Airport', 'South Kellyberg', 'Arkansas', 'Croatia', 'IZA', 'UTC+4');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('Lake John International Airport', 'North Stephen', 'Louisiana', 'Saint Pierre and Miquelon', 'FEU', 'UTC-10');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('West Laurie International Airport', 'Cuevasborough', 'Ohio', 'Bermuda', 'HIO', 'UTC+10');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('North Jenniferland International Airport', 'East Zacharybury', 'New Mexico', 'Belgium', 'KCS', 'UTC-1');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('Jamesberg International Airport', 'New Ashleyborough', 'Minnesota', 'Kiribati', 'UTR', 'UTC+9');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('Lake Kathleen International Airport', 'South Lori', 'Idaho', 'Mauritius', 'WDM', 'UTC-10');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('Victorport International Airport', 'Port Ginaburgh', 'Massachusetts', 'Saint Martin', 'DHN', 'UTC+9');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('Victoriaport International Airport', 'Jameshaven', 'Georgia', 'Guadeloupe', 'WHX', 'UTC-10');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('Port Rebeccaberg International Airport', 'Manningfurt', 'Nevada', 'Haiti', 'JAF', 'UTC+11');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('Sherryfurt International Airport', 'Kevinland', 'Idaho', 'Equatorial Guinea', 'PON', 'UTC+10');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('East Janetville International Airport', 'Nicholsview', 'New Mexico', 'New Zealand', 'HIK', 'UTC+11');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('New Katherineside International Airport', 'East Rose', 'Indiana', 'Samoa', 'IRP', 'UTC-4');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('West Nicolemouth International Airport', 'Millerton', 'New York', 'Guadeloupe', 'JOE', 'UTC-1');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('Newmanland International Airport', 'North Christianhaven', 'West Virginia', 'Slovakia (Slovak Republic)', 'ADV', 'UTC-5');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('Nancychester International Airport', 'Port John', 'Wisconsin', 'Italy', 'XPZ', 'UTC+6');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('South Caleb International Airport', 'Danielberg', 'Alaska', 'Cayman Islands', 'IMD', 'UTC-4');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('West Johnfurt International Airport', 'South Kyle', 'New Mexico', 'Syrian Arab Republic', 'QSZ', 'UTC-3');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('Davidchester International Airport', 'East Crystal', 'Massachusetts', 'Holy See (Vatican City State)', 'UIO', 'UTC-6');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('Jenniferchester International Airport', 'Leestad', 'Nevada', 'Djibouti', 'RST', 'UTC-4');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('West Jessica International Airport', 'Lake Jennifer', 'Utah', 'Ethiopia', 'OEA', 'UTC-4');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('Port Dennisstad International Airport', 'Andersonland', 'Washington', 'Turkmenistan', 'QXJ', 'UTC-6');
INSERT INTO AIRPORT (name, city, region, country, iata_code, timezone) VALUES ('West Johnshire International Airport', 'East Michaelland', 'West Virginia', 'Gambia', 'GCA', 'UTC-8');

-- Table: ROUTE
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (41, 73);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (46, 72);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (80, 20);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (59, 49);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (23, 14);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (92, 89);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (7, 31);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (34, 39);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (68, 44);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (34, 42);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (49, 35);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (38, 14);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (1, 20);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (46, 44);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (83, 4);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (31, 77);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (94, 20);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (30, 9);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (95, 69);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (83, 75);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (31, 14);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (46, 80);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (54, 31);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (83, 97);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (64, 45);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (94, 1);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (1, 58);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (89, 13);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (19, 92);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (38, 31);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (2, 89);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (66, 62);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (4, 30);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (30, 23);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (8, 62);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (12, 38);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (16, 35);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (57, 84);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (66, 57);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (17, 32);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (83, 24);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (51, 36);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (1, 36);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (35, 11);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (89, 6);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (13, 29);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (43, 80);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (85, 62);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (69, 59);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (13, 55);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (85, 9);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (82, 53);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (51, 25);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (3, 51);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (77, 44);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (81, 11);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (28, 64);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (15, 39);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (10, 91);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (56, 99);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (42, 64);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (22, 37);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (34, 62);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (88, 50);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (95, 84);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (50, 26);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (29, 35);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (95, 94);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (59, 38);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (81, 10);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (15, 76);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (88, 29);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (24, 47);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (64, 72);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (93, 6);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (38, 95);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (67, 23);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (25, 78);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (12, 84);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (8, 56);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (63, 54);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (3, 56);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (99, 7);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (38, 23);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (84, 78);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (20, 56);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (62, 35);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (39, 2);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (21, 60);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (20, 60);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (60, 76);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (34, 53);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (67, 16);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (54, 5);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (82, 85);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (46, 44);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (56, 96);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (71, 4);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (49, 23);
INSERT INTO ROUTE (origin_airport_id, destination_airport_id) VALUES (62, 100);

-- Table: AIRCRAFT
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('777', 'Boeing', 278, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('E190', 'Embraer', 262, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('E190', 'Embraer', 383, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('E195', 'Embraer', 294, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('A320', 'Airbus', 287, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('777', 'Boeing', 412, 'Maintenance');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('A350', 'Airbus', 439, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('737', 'Boeing', 170, 'Maintenance');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('E190', 'Embraer', 357, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('E190', 'Embraer', 241, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('E195', 'Embraer', 365, 'Maintenance');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('A320', 'Airbus', 166, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('A350', 'Airbus', 187, 'Maintenance');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('E190', 'Embraer', 351, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('A320', 'Airbus', 438, 'Maintenance');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('747', 'Boeing', 302, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('A320', 'Airbus', 433, 'Maintenance');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('A350', 'Airbus', 354, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('E195', 'Embraer', 258, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('E190', 'Embraer', 185, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('A350', 'Airbus', 392, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('A350', 'Airbus', 84, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('A330', 'Airbus', 392, 'Maintenance');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('787', 'Boeing', 373, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('A380', 'Airbus', 174, 'Maintenance');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('737', 'Boeing', 430, 'Maintenance');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('E195', 'Embraer', 413, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('E190', 'Embraer', 384, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('737', 'Boeing', 208, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('A350', 'Airbus', 210, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('737', 'Boeing', 367, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('A320', 'Airbus', 448, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('A330', 'Airbus', 350, 'Maintenance');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('777', 'Boeing', 265, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('A350', 'Airbus', 252, 'Maintenance');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('E190', 'Embraer', 261, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('E190', 'Embraer', 434, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('737', 'Boeing', 230, 'Maintenance');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('777', 'Boeing', 151, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('777', 'Boeing', 200, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('E190', 'Embraer', 429, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('747', 'Boeing', 333, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('E195', 'Embraer', 135, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('E195', 'Embraer', 148, 'Maintenance');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('A320', 'Airbus', 235, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('A350', 'Airbus', 392, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('747', 'Boeing', 255, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('747', 'Boeing', 186, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('787', 'Boeing', 371, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('747', 'Boeing', 407, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('E195', 'Embraer', 355, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('A330', 'Airbus', 215, 'Maintenance');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('787', 'Boeing', 275, 'Maintenance');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('747', 'Boeing', 197, 'Maintenance');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('A350', 'Airbus', 376, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('A330', 'Airbus', 300, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('E190', 'Embraer', 385, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('A380', 'Airbus', 227, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('787', 'Boeing', 100, 'Maintenance');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('A380', 'Airbus', 164, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('E190', 'Embraer', 347, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('A320', 'Airbus', 325, 'Maintenance');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('E190', 'Embraer', 277, 'Maintenance');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('737', 'Boeing', 422, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('777', 'Boeing', 97, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('E190', 'Embraer', 380, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('747', 'Boeing', 96, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('E195', 'Embraer', 353, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('747', 'Boeing', 207, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('A350', 'Airbus', 87, 'Maintenance');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('787', 'Boeing', 164, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('E190', 'Embraer', 180, 'Maintenance');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('737', 'Boeing', 155, 'Maintenance');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('E190', 'Embraer', 310, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('A330', 'Airbus', 230, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('737', 'Boeing', 321, 'Maintenance');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('777', 'Boeing', 340, 'Maintenance');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('E190', 'Embraer', 120, 'Maintenance');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('E190', 'Embraer', 366, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('E190', 'Embraer', 284, 'Maintenance');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('A320', 'Airbus', 320, 'Maintenance');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('737', 'Boeing', 276, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('777', 'Boeing', 248, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('E190', 'Embraer', 95, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('E190', 'Embraer', 294, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('E190', 'Embraer', 287, 'Maintenance');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('777', 'Boeing', 181, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('A380', 'Airbus', 223, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('737', 'Boeing', 270, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('787', 'Boeing', 116, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('A330', 'Airbus', 84, 'Maintenance');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('E195', 'Embraer', 277, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('A350', 'Airbus', 431, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('A330', 'Airbus', 406, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('A320', 'Airbus', 398, 'Maintenance');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('747', 'Boeing', 419, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('787', 'Boeing', 180, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('E195', 'Embraer', 377, 'Active');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('777', 'Boeing', 410, 'Maintenance');
INSERT INTO AIRCRAFT (model, manufacturer, capacity, status) VALUES ('777', 'Boeing', 160, 'Active');

-- Table: FLIGHT
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('NZ-9135', '2026-11-28 05:10:48', '2026-11-28 11:10:48', 'Delayed', 74, 94);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('OG-9812', '2026-04-09 07:12:40', '2026-04-09 18:12:40', 'Scheduled', 21, 17);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('QJ-9989', '2026-05-28 04:34:22', '2026-05-28 16:34:22', 'Scheduled', 48, 67);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('HZ-7787', '2026-07-08 23:25:19', '2026-07-09 03:25:19', 'Delayed', 2, 74);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('AY-7139', '2026-09-10 10:01:30', '2026-09-10 17:01:30', 'On Time', 61, 3);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('VM-3873', '2026-04-12 03:25:00', '2026-04-12 06:25:00', 'Scheduled', 30, 21);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('DY-4498', '2026-11-19 08:39:10', '2026-11-19 12:39:10', 'On Time', 60, 21);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('VF-6315', '2026-09-13 11:49:33', '2026-09-13 17:49:33', 'On Time', 41, 65);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('HJ-4230', '2026-08-07 22:49:48', '2026-08-08 06:49:48', 'Delayed', 3, 80);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('RC-6259', '2026-12-06 06:29:23', '2026-12-06 08:29:23', 'Scheduled', 4, 5);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('QS-9592', '2026-07-15 12:43:34', '2026-07-15 21:43:34', 'On Time', 25, 50);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('RU-4431', '2026-06-20 20:01:28', '2026-06-21 01:01:28', 'Scheduled', 91, 29);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('QN-4523', '2026-07-10 04:57:21', '2026-07-10 12:57:21', 'Delayed', 28, 32);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('DZ-5220', '2026-05-09 18:33:50', '2026-05-09 20:33:50', 'Delayed', 10, 60);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('FW-7540', '2026-11-18 21:30:59', '2026-11-19 02:30:59', 'Delayed', 13, 35);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('GG-7119', '2026-04-08 13:32:54', '2026-04-08 20:32:54', 'Scheduled', 72, 13);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('HV-8900', '2026-10-02 00:08:18', '2026-10-02 12:08:18', 'On Time', 1, 88);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('GS-0042', '2026-09-25 00:15:52', '2026-09-25 05:15:52', 'Scheduled', 5, 86);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('WW-6023', '2026-05-07 18:46:36', '2026-05-07 21:46:36', 'Delayed', 6, 23);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('EH-7584', '2026-09-17 21:14:18', '2026-09-18 05:14:18', 'Scheduled', 72, 77);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('HF-3064', '2026-10-08 08:00:27', '2026-10-08 19:00:27', 'Scheduled', 78, 65);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('NT-1434', '2026-06-15 01:54:11', '2026-06-15 09:54:11', 'Scheduled', 70, 47);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('ZF-9047', '2026-07-10 20:49:56', '2026-07-11 01:49:56', 'Delayed', 38, 59);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('MQ-8200', '2026-05-10 13:50:33', '2026-05-10 19:50:33', 'Delayed', 61, 98);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('TL-3749', '2026-05-19 02:54:36', '2026-05-19 05:54:36', 'On Time', 35, 72);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('KA-8931', '2026-10-11 05:34:59', '2026-10-11 07:34:59', 'On Time', 75, 95);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('GX-8789', '2026-11-25 16:32:22', '2026-11-26 02:32:22', 'On Time', 64, 61);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('AN-2241', '2026-11-10 01:56:16', '2026-11-10 02:56:16', 'On Time', 96, 64);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('TI-6015', '2026-05-02 04:06:51', '2026-05-02 14:06:51', 'Delayed', 41, 99);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('FI-5769', '2026-06-21 17:24:25', '2026-06-21 22:24:25', 'Delayed', 23, 73);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('ZC-1201', '2026-05-07 05:40:33', '2026-05-07 17:40:33', 'On Time', 16, 31);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('TB-3939', '2026-05-16 01:29:45', '2026-05-16 12:29:45', 'On Time', 64, 36);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('XS-9327', '2026-09-14 12:44:06', '2026-09-14 21:44:06', 'Delayed', 12, 25);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('MT-7193', '2026-09-23 07:17:46', '2026-09-23 15:17:46', 'On Time', 92, 75);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('IW-0862', '2026-09-03 05:51:38', '2026-09-03 09:51:38', 'Scheduled', 56, 41);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('IG-3713', '2026-06-27 07:09:24', '2026-06-27 18:09:24', 'Scheduled', 33, 43);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('CN-6307', '2026-06-14 11:49:03', '2026-06-14 16:49:03', 'On Time', 22, 82);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('AS-2099', '2026-08-15 07:10:47', '2026-08-15 14:10:47', 'Delayed', 30, 13);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('UU-7395', '2026-04-08 08:09:34', '2026-04-08 13:09:34', 'Delayed', 45, 82);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('EX-6228', '2026-09-30 04:52:00', '2026-09-30 13:52:00', 'Delayed', 17, 98);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('QG-7671', '2026-12-13 21:17:32', '2026-12-14 06:17:32', 'Delayed', 53, 48);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('KI-9037', '2026-11-29 09:30:00', '2026-11-29 17:30:00', 'Scheduled', 98, 26);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('DC-7993', '2026-06-25 19:34:31', '2026-06-25 22:34:31', 'Scheduled', 65, 95);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('CC-3518', '2026-06-19 13:15:21', '2026-06-19 18:15:21', 'Delayed', 96, 75);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('GZ-6498', '2026-11-03 11:04:15', '2026-11-03 21:04:15', 'Scheduled', 19, 15);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('HD-9089', '2026-12-26 11:22:17', '2026-12-26 20:22:17', 'On Time', 49, 36);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('YD-5095', '2026-06-21 02:05:41', '2026-06-21 06:05:41', 'Scheduled', 60, 63);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('GE-8853', '2026-07-25 08:07:45', '2026-07-25 17:07:45', 'Scheduled', 14, 94);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('NI-5779', '2026-08-04 03:25:21', '2026-08-04 11:25:21', 'On Time', 12, 93);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('BT-5771', '2026-07-16 16:37:26', '2026-07-16 22:37:26', 'Delayed', 21, 6);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('PG-9804', '2026-07-21 20:59:20', '2026-07-22 05:59:20', 'Delayed', 75, 29);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('AU-5658', '2026-11-12 19:56:23', '2026-11-13 02:56:23', 'On Time', 7, 9);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('AQ-9494', '2026-05-14 05:50:23', '2026-05-14 17:50:23', 'Delayed', 100, 6);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('DK-5300', '2026-05-18 04:52:35', '2026-05-18 16:52:35', 'Scheduled', 65, 90);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('ZK-1595', '2026-09-05 08:45:46', '2026-09-05 18:45:46', 'On Time', 21, 96);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('YF-4810', '2026-12-14 07:34:40', '2026-12-14 17:34:40', 'Delayed', 72, 37);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('PV-1265', '2026-09-27 10:03:41', '2026-09-27 11:03:41', 'On Time', 5, 82);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('CH-9490', '2026-09-04 16:13:48', '2026-09-04 17:13:48', 'On Time', 99, 65);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('DP-2407', '2026-06-17 08:27:41', '2026-06-17 18:27:41', 'Delayed', 49, 29);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('HY-5674', '2026-05-26 08:15:05', '2026-05-26 18:15:05', 'Delayed', 99, 74);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('VE-6293', '2026-09-24 02:07:52', '2026-09-24 12:07:52', 'Delayed', 44, 41);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('MO-0450', '2026-04-14 03:40:54', '2026-04-14 10:40:54', 'On Time', 96, 45);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('QL-6156', '2026-10-13 21:31:34', '2026-10-14 04:31:34', 'On Time', 47, 63);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('KC-3889', '2026-11-01 12:05:07', '2026-11-01 21:05:07', 'Scheduled', 30, 69);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('IZ-0041', '2026-10-28 17:32:28', '2026-10-28 22:32:28', 'On Time', 30, 10);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('BY-4598', '2026-07-18 19:06:45', '2026-07-19 00:06:45', 'Scheduled', 74, 96);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('WZ-8478', '2026-12-13 02:59:03', '2026-12-13 07:59:03', 'On Time', 16, 13);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('JW-6611', '2026-05-25 21:03:06', '2026-05-26 03:03:06', 'Delayed', 99, 76);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('HK-1893', '2026-12-04 16:45:42', '2026-12-05 03:45:42', 'Delayed', 74, 17);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('EN-7498', '2026-08-05 11:07:29', '2026-08-05 18:07:29', 'Scheduled', 90, 100);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('UL-1656', '2026-08-15 14:03:28', '2026-08-15 18:03:28', 'Delayed', 3, 14);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('RF-6549', '2026-08-26 21:38:27', '2026-08-26 23:38:27', 'On Time', 94, 32);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('WB-1127', '2026-09-21 23:38:10', '2026-09-22 04:38:10', 'On Time', 93, 33);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('JO-4148', '2026-08-22 21:22:30', '2026-08-22 23:22:30', 'Scheduled', 89, 69);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('NA-4024', '2026-08-07 23:45:23', '2026-08-08 01:45:23', 'Scheduled', 17, 45);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('GI-1212', '2026-12-31 10:11:59', '2026-12-31 14:11:59', 'Delayed', 74, 22);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('WO-1599', '2026-12-12 11:21:38', '2026-12-12 19:21:38', 'On Time', 76, 5);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('RG-8952', '2026-04-19 19:01:53', '2026-04-19 23:01:53', 'Scheduled', 60, 45);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('ZV-6795', '2026-08-05 10:40:42', '2026-08-05 16:40:42', 'On Time', 56, 15);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('XL-9672', '2026-10-23 21:18:21', '2026-10-23 22:18:21', 'Delayed', 38, 27);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('OX-7646', '2026-11-06 18:19:25', '2026-11-07 02:19:25', 'Delayed', 66, 85);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('FL-6219', '2026-12-08 00:48:18', '2026-12-08 12:48:18', 'On Time', 51, 41);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('IK-2986', '2026-10-12 06:08:50', '2026-10-12 09:08:50', 'Delayed', 5, 57);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('XD-3998', '2026-04-01 00:27:44', '2026-04-01 09:27:44', 'Delayed', 49, 35);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('OZ-1365', '2026-12-03 02:23:41', '2026-12-03 12:23:41', 'Delayed', 23, 18);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('MW-0875', '2026-04-12 00:32:28', '2026-04-12 10:32:28', 'Delayed', 94, 11);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('EA-7956', '2026-09-10 20:05:24', '2026-09-10 22:05:24', 'Scheduled', 10, 94);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('LW-2630', '2026-08-17 14:59:14', '2026-08-17 23:59:14', 'Delayed', 69, 18);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('UB-2658', '2026-10-21 13:24:31', '2026-10-21 18:24:31', 'Delayed', 99, 49);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('XJ-1129', '2026-12-01 20:38:58', '2026-12-02 01:38:58', 'Delayed', 99, 24);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('NV-8962', '2026-08-07 10:24:34', '2026-08-07 18:24:34', 'Delayed', 9, 30);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('ZP-0866', '2026-07-11 11:40:37', '2026-07-11 17:40:37', 'Scheduled', 90, 92);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('FG-8876', '2026-12-03 01:36:51', '2026-12-03 09:36:51', 'On Time', 95, 91);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('AS-8309', '2026-09-27 18:50:48', '2026-09-28 03:50:48', 'Delayed', 43, 22);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('SD-8152', '2026-05-27 03:59:07', '2026-05-27 14:59:07', 'Delayed', 39, 27);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('UP-8996', '2026-11-27 12:37:03', '2026-11-27 22:37:03', 'Scheduled', 23, 36);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('XW-3700', '2026-09-01 15:14:22', '2026-09-01 18:14:22', 'Delayed', 72, 19);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('PO-7883', '2026-12-23 05:28:47', '2026-12-23 11:28:47', 'On Time', 68, 37);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('CB-6242', '2026-06-09 21:46:37', '2026-06-10 09:46:37', 'Delayed', 46, 97);
INSERT INTO FLIGHT (flight_number, departure_time, arrival_time, status, route_id, aircraft_id) VALUES ('BH-8727', '2026-06-15 06:04:26', '2026-06-15 18:04:26', 'On Time', 44, 100);

-- Table: TERMINAL
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal North', '6', 10444, 26);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal North', '2', 13245, 18);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal South', '5', 8735, 45);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal South', '2', 13610, 69);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal Alpha', '1', 12974, 58);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal C', '4', 12087, 70);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal C', '4', 13352, 59);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal North', '6', 6955, 88);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal South', '5', 5167, 96);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal North', '3', 10588, 47);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal North', '3', 9230, 8);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal Alpha', '1', 7025, 34);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal North', '3', 12805, 15);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal South', '5', 4462, 98);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal North', '4', 7101, 96);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal C', '4', 10913, 70);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal Bravo', '1', 13636, 68);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal Alpha', '6', 7961, 19);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal Alpha', '3', 4721, 10);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal North', '5', 10782, 84);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal South', '2', 5207, 84);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal North', '4', 8590, 38);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal Alpha', '4', 10993, 73);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal Alpha', '4', 11069, 25);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal Bravo', '2', 2892, 38);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal South', '2', 11724, 33);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal C', '2', 4674, 75);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal North', '3', 9693, 37);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal C', '3', 5636, 27);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal South', '5', 3923, 59);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal Bravo', '4', 4554, 33);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal C', '5', 2169, 49);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal South', '4', 2955, 1);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal North', '1', 10039, 64);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal Alpha', '1', 3248, 13);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal C', '4', 10678, 60);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal Alpha', '6', 3554, 77);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal C', '5', 6063, 29);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal C', '1', 8390, 37);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal C', '4', 4799, 29);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal C', '5', 4089, 46);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal Bravo', '6', 6828, 100);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal Alpha', '5', 5465, 77);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal North', '5', 9897, 44);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal C', '1', 11653, 93);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal South', '2', 5681, 31);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal South', '1', 8747, 52);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal Bravo', '5', 5167, 60);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal C', '4', 7509, 91);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal Bravo', '2', 12131, 75);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal C', '3', 7459, 34);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal South', '3', 7427, 23);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal C', '5', 2323, 100);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal C', '4', 3206, 54);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal Bravo', '2', 14276, 94);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal South', '4', 6915, 36);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal South', '6', 14667, 87);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal North', '2', 11331, 97);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal C', '3', 5841, 91);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal Bravo', '4', 11575, 32);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal C', '4', 9660, 65);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal Alpha', '1', 2823, 20);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal North', '1', 14261, 4);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal Alpha', '6', 4779, 42);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal Bravo', '2', 7083, 44);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal South', '6', 10080, 89);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal C', '3', 3385, 70);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal South', '4', 13682, 87);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal Bravo', '4', 2955, 16);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal North', '4', 7308, 24);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal North', '5', 4782, 55);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal Bravo', '2', 6804, 38);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal C', '3', 7461, 80);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal North', '3', 12934, 43);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal Alpha', '6', 11950, 22);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal North', '6', 14332, 26);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal North', '4', 14506, 13);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal North', '3', 8402, 19);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal Bravo', '5', 10816, 50);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal C', '3', 11156, 52);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal Bravo', '2', 5473, 45);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal South', '5', 8651, 37);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal Alpha', '1', 7213, 23);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal North', '4', 8870, 93);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal South', '4', 6272, 14);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal South', '2', 12601, 47);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal C', '6', 2405, 75);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal Bravo', '1', 14261, 57);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal C', '4', 13475, 40);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal Alpha', '4', 14566, 80);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal South', '6', 5750, 7);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal South', '4', 2814, 59);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal South', '6', 4790, 82);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal C', '1', 6516, 73);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal C', '1', 14533, 45);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal C', '3', 7172, 46);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal Bravo', '6', 14357, 49);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal South', '6', 7140, 89);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal South', '1', 4347, 5);
INSERT INTO TERMINAL (terminal_name, terminal_number, capacity, airport_id) VALUES ('Terminal Bravo', '2', 2295, 18);

-- Table: GATE
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('A10', 'Closed', 170, 38);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('A4', 'Closed', 338, 88);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('A24', 'Closed', 350, 8);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('B3', 'Under Cleaning', 288, 13);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('B10', 'Open', 325, 49);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('B20', 'Closed', 260, 42);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('A20', 'Open', 276, 41);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('G13', 'Under Cleaning', 194, 99);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('A18', 'Open', 145, 52);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('G6', 'Closed', 331, 45);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('B36', 'Under Cleaning', 172, 47);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('B36', 'Under Cleaning', 317, 72);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('B22', 'Open', 224, 29);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('A21', 'Open', 200, 5);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('A40', 'Open', 126, 50);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('G27', 'Open', 160, 37);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('A33', 'Under Cleaning', 280, 96);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('A29', 'Closed', 329, 91);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('G26', 'Closed', 191, 64);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('A36', 'Under Cleaning', 203, 26);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('G19', 'Open', 239, 27);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('A30', 'Under Cleaning', 175, 85);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('A25', 'Open', 137, 53);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('G37', 'Open', 144, 82);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('B10', 'Under Cleaning', 291, 6);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('A30', 'Under Cleaning', 244, 40);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('A34', 'Closed', 279, 80);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('A7', 'Under Cleaning', 338, 82);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('A23', 'Open', 348, 72);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('G9', 'Closed', 148, 39);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('A30', 'Open', 227, 13);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('B33', 'Open', 346, 70);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('B36', 'Closed', 280, 51);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('G26', 'Under Cleaning', 282, 2);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('G6', 'Closed', 136, 31);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('B19', 'Under Cleaning', 136, 42);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('B35', 'Open', 180, 18);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('G3', 'Closed', 267, 62);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('G25', 'Under Cleaning', 350, 91);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('G23', 'Open', 198, 73);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('A31', 'Open', 165, 56);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('G34', 'Under Cleaning', 309, 30);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('G22', 'Closed', 239, 50);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('A34', 'Under Cleaning', 307, 52);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('A3', 'Under Cleaning', 269, 17);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('G33', 'Under Cleaning', 292, 69);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('B15', 'Open', 332, 5);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('G6', 'Open', 144, 51);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('B10', 'Under Cleaning', 270, 94);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('G39', 'Open', 115, 94);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('B35', 'Under Cleaning', 233, 86);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('B37', 'Open', 272, 82);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('A1', 'Under Cleaning', 244, 52);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('G36', 'Under Cleaning', 239, 94);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('B24', 'Open', 293, 78);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('G12', 'Open', 215, 86);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('B30', 'Under Cleaning', 327, 3);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('B31', 'Closed', 326, 12);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('A27', 'Closed', 158, 50);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('G17', 'Open', 221, 74);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('B21', 'Closed', 106, 55);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('G19', 'Closed', 106, 57);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('G29', 'Closed', 206, 45);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('B3', 'Open', 265, 72);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('B6', 'Open', 136, 99);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('A19', 'Closed', 223, 27);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('G11', 'Closed', 188, 3);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('A13', 'Open', 274, 20);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('G18', 'Closed', 315, 84);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('A19', 'Closed', 332, 48);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('B25', 'Open', 191, 49);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('B34', 'Open', 130, 24);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('A18', 'Closed', 169, 33);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('B14', 'Open', 231, 87);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('A38', 'Under Cleaning', 273, 86);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('A36', 'Open', 321, 1);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('G33', 'Open', 128, 66);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('G30', 'Open', 138, 89);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('G13', 'Closed', 296, 95);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('B11', 'Closed', 228, 15);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('B32', 'Under Cleaning', 267, 17);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('G20', 'Closed', 103, 33);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('G29', 'Open', 197, 99);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('A18', 'Open', 134, 82);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('B8', 'Closed', 340, 71);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('A5', 'Closed', 177, 33);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('G5', 'Open', 123, 93);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('A12', 'Under Cleaning', 314, 73);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('G5', 'Open', 142, 61);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('A26', 'Under Cleaning', 173, 38);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('G33', 'Open', 275, 90);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('B32', 'Open', 202, 31);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('G10', 'Open', 159, 67);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('B36', 'Open', 221, 100);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('A19', 'Closed', 149, 61);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('B4', 'Closed', 185, 18);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('B17', 'Closed', 260, 79);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('B11', 'Closed', 269, 42);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('G27', 'Under Cleaning', 267, 45);
INSERT INTO GATE (gate_number, status, max_passengers, terminal_id) VALUES ('A7', 'Under Cleaning', 160, 24);
