-- -----------------------------------------------------
-- Table AIRPORT
-- -----------------------------------------------------
CREATE TABLE AIRPORT (
  airport_id INT GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(255) NOT NULL,
  city VARCHAR(100) NOT NULL,
  region VARCHAR(100),
  country VARCHAR(100) NOT NULL,
  iata_code CHAR(3) NOT NULL,
  timezone VARCHAR(50) NOT NULL,
  PRIMARY KEY (airport_id),
  UNIQUE (iata_code)
);

COMMENT ON TABLE AIRPORT IS 'Stores information about international and domestic airports.';
COMMENT ON COLUMN AIRPORT.iata_code IS '3-letter IATA location identifier (e.g., LAX, LHR).';

-- -----------------------------------------------------
-- Table ROUTE
-- -----------------------------------------------------
CREATE TABLE ROUTE (
  route_id INT GENERATED BY DEFAULT AS IDENTITY,
  origin_airport_id INT NOT NULL,
  destination_airport_id INT NOT NULL,
  PRIMARY KEY (route_id),
  FOREIGN KEY (origin_airport_id) REFERENCES AIRPORT(airport_id),
  FOREIGN KEY (destination_airport_id) REFERENCES AIRPORT(airport_id),
  -- Prevent a route from having the same origin and destination
  CONSTRAINT check_different_airports CHECK (origin_airport_id <> destination_airport_id)
);

COMMENT ON TABLE ROUTE IS 'Defines paths between two specific airports.';

-- -----------------------------------------------------
-- Table AIRCRAFT
-- -----------------------------------------------------
CREATE TABLE AIRCRAFT (
  aircraft_id INT GENERATED BY DEFAULT AS IDENTITY,
  model VARCHAR(100) NOT NULL,
  manufacturer VARCHAR(100) NOT NULL,
  capacity INT NOT NULL CHECK (capacity > 0),
  status VARCHAR(50) NOT NULL,
  PRIMARY KEY (aircraft_id)
);

COMMENT ON TABLE AIRCRAFT IS 'Physical aircraft fleet management.';
COMMENT ON COLUMN AIRCRAFT.status IS 'Current operational state (e.g., Active, Maintenance, Retired).';

-- -----------------------------------------------------
-- Table FLIGHT
-- -----------------------------------------------------
CREATE TABLE FLIGHT (
  flight_id INT GENERATED BY DEFAULT AS IDENTITY,
  flight_number VARCHAR(20) NOT NULL,
  departure_time TIMESTAMP WITH TIME ZONE NOT NULL,
  arrival_time TIMESTAMP WITH TIME ZONE NOT NULL,
  status VARCHAR(50) NOT NULL,
  route_id INT NOT NULL,
  aircraft_id INT NOT NULL,
  PRIMARY KEY (flight_id),
  FOREIGN KEY (route_id) REFERENCES ROUTE(route_id),
  FOREIGN KEY (aircraft_id) REFERENCES AIRCRAFT(aircraft_id),
  UNIQUE (flight_number),
  CONSTRAINT check_flight_times CHECK (arrival_time > departure_time)
);

COMMENT ON TABLE FLIGHT IS 'Individual scheduled flights linked to routes and aircraft.';

-- -----------------------------------------------------
-- Table TERMINAL
-- -----------------------------------------------------
CREATE TABLE TERMINAL (
  terminal_id INT GENERATED BY DEFAULT AS IDENTITY,
  terminal_name VARCHAR(100) NOT NULL,
  terminal_number VARCHAR(10) NOT NULL,
  capacity INT NOT NULL,
  airport_id INT NOT NULL,
  PRIMARY KEY (terminal_id),
  FOREIGN KEY (airport_id) REFERENCES AIRPORT(airport_id)
);

COMMENT ON TABLE TERMINAL IS 'Airport terminal buildings.';

-- -----------------------------------------------------
-- Table GATE
-- -----------------------------------------------------
CREATE TABLE GATE (
  gate_id INT GENERATED BY DEFAULT AS IDENTITY,
  gate_number VARCHAR(10) NOT NULL,
  status VARCHAR(50) NOT NULL,
  max_passengers INT NOT NULL,
  terminal_id INT NOT NULL,
  PRIMARY KEY (gate_id),
  FOREIGN KEY (terminal_id) REFERENCES TERMINAL(terminal_id)
);

COMMENT ON TABLE GATE IS 'Specific boarding gates within a terminal.';