insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Mamitupo Airport', 'Banjar Buahan', null, 'Indonesia', 'MPI', 'Asia/Makassar');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('St Cloud Regional Airport', 'Bulog', null, 'Philippines', 'STC', 'Asia/Manila');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Mekele Airport', 'Leones', null, 'Argentina', 'MQX', 'America/Argentina/Cordoba');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Capitan FAP Carlos Martinez De Pinillos International Airport', 'Shishang', null, 'China', 'TRU', 'Asia/Shanghai');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('San Gabriel Valley Airport', 'Ngawi', null, 'Indonesia', 'EMT', 'Asia/Jakarta');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Bouaké Airport', 'Za‘tarah', null, 'Palestinian Territory', 'BYK', 'Asia/Hebron');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Keetmanshoop Airport', 'Yezhi', null, 'China', 'KMP', 'Asia/Chongqing');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Aitutaki Airport', 'Nancy', 'Lorraine', 'France', 'AIT', 'Europe/Paris');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Green River Municipal Airport', 'Bao’an', null, 'China', 'RVR', 'Asia/Shanghai');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Pomala Airport', 'Thị Trấn Quảng Uyên', null, 'Vietnam', 'PUM', 'Asia/Ho_Chi_Minh');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Greenville Downtown Airport', 'Gumuk Tengah', null, 'Indonesia', 'GMU', 'Asia/Jakarta');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Dourados Airport', 'Qujiang', null, 'China', 'DOU', 'Asia/Chongqing');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Arnold Air Force Base', 'El Tambo', null, 'Colombia', 'TUH', 'America/Bogota');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Baie Comeau Airport', 'Suvorovskaya', null, 'Russia', 'YBC', 'Europe/Moscow');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Mmabatho International Airport', 'La Condamine', null, 'Monaco', 'MBD', 'Europe/Monaco');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Mariposa Yosemite Airport', 'Piancheng', null, 'China', 'RMY', 'Asia/Chongqing');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Bateen Airport', 'Rîbniţa', null, 'Moldova', 'AZI', 'Europe/Chisinau');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Kuujjuarapik Airport', 'Outokumpu', null, 'Finland', 'YGW', 'Europe/Helsinki');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Perry Island Seaplane Base', 'Isiolo', null, 'Kenya', 'PYL', 'Africa/Nairobi');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Braga Municipal Aerodrome', 'Xieba', null, 'China', 'BGZ', 'Asia/Chongqing');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Les Bases Airport', 'Zhezqazghan', null, 'Kazakhstan', 'GBJ', 'Asia/Almaty');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Big Lake Airport', 'Chiri-Yurt', null, 'Russia', 'BGQ', 'Europe/Moscow');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Kelle Airport', 'Karangbungur', null, 'Indonesia', 'KEE', 'Asia/Jakarta');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Jinchuan Airport', 'Évry', 'Île-de-France', 'France', 'JIC', 'Europe/Paris');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Polokwane International Airport', 'Waajid', null, 'Somalia', 'PTG', 'Africa/Mogadishu');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Ascona Airport', 'Binglincha', null, 'China', 'ACO', 'Asia/Chongqing');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Professor Urbano Ernesto Stumpf Airport', 'Gazli', null, 'Uzbekistan', 'SJK', 'Asia/Samarkand');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('St Cloud Regional Airport', 'Padaimut', null, 'Indonesia', 'STC', 'Asia/Jakarta');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Augsburg Airport', 'Yafran', null, 'Libya', 'AGB', 'Africa/Tripoli');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Tsletsi Airport', 'Kōfu-shi', null, 'Japan', 'QDJ', 'Asia/Tokyo');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Temora Airport', 'Rozhnyativ', null, 'Ukraine', 'TEM', 'Europe/Uzhgorod');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Zhukovsky International Airport', 'Wangyi Zhendian', null, 'China', 'ZIA', 'Asia/Chongqing');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Mc Alester Regional Airport', 'Glamoč', null, 'Bosnia and Herzegovina', 'MLC', 'Europe/Sarajevo');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Sila Airport', 'Barbacena', null, 'Brazil', 'SIL', 'America/Sao_Paulo');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Northwest Florida Beaches International Airport', 'Aurora', null, 'Philippines', 'ECP', 'Asia/Manila');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Luxembourg-Findel International Airport', 'Meilisi', null, 'China', 'LUX', 'Asia/Harbin');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Renner Field-Goodland Municipal Airport', 'Greenville', 'South Carolina', 'United States', 'GLD', 'America/New_York');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Namatanai Airport', 'Béziers', 'Languedoc-Roussillon', 'France', 'ATN', 'Europe/Paris');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Higuerote Airport', 'Blora', null, 'Indonesia', 'HGE', 'Asia/Jakarta');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Orestes Acosta Airport', 'Barra', null, 'Brazil', 'MOA', 'America/Bahia');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Dongying Shengli Airport', 'Bantacan', null, 'Philippines', 'DOY', 'Asia/Manila');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Nanping Wuyishan Airport', 'Dafundo', 'Lisboa', 'Portugal', 'WUS', 'Europe/Lisbon');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Vanua Balavu Airport', 'K’anak’erravan', null, 'Armenia', 'VBV', 'Asia/Yerevan');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Sligo Airport', 'Tríkala', null, 'Greece', 'SXL', 'Europe/Athens');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Domodedovo International Airport', 'Santai', null, 'China', 'DME', 'Asia/Urumqi');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Shishmaref Airport', 'Syktyvkar', null, 'Russia', 'SHH', 'Europe/Moscow');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Mornington Island Airport', 'Norsborg', 'Stockholm', 'Sweden', 'ONG', 'Europe/Stockholm');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('West Woodward Airport', 'Springfield', 'Missouri', 'United States', 'WWR', 'America/Chicago');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Milano Linate Airport', 'Fengpo', null, 'China', 'LIN', 'Asia/Chongqing');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Rabil Airport', 'Mompós', null, 'Colombia', 'BVC', 'America/Bogota');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Block Island State Airport', 'Rondonópolis', null, 'Brazil', 'BID', 'America/Cuiaba');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Wanxian Airport', 'Plyeshchanitsy', null, 'Belarus', 'WXN', 'Europe/Minsk');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Sofia Airport', 'Houston', 'Texas', 'United States', 'SOF', 'America/Chicago');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('San Pedro Airport', 'Ōtsu-shi', null, 'Japan', 'SPR', 'Asia/Tokyo');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Beaver Creek Airport', 'Seixo de Manhoses', 'Bragança', 'Portugal', 'YXQ', 'Europe/Lisbon');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Karlsruhe Baden-Baden Airport', 'Maralal', null, 'Kenya', 'FKB', 'Africa/Nairobi');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Lianshui Airport', 'Iquipi', null, 'Peru', 'HIA', 'America/Lima');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Villacoublay-Vélizy (BA 107) Air Base', 'Dąbrowa', null, 'Poland', 'VIY', 'Europe/Warsaw');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Ostend-Bruges International Airport', 'Los Fresnos', 'Guanajuato', 'Mexico', 'OST', 'America/Mexico_City');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Sidney Municipal-Lloyd W Carr Field', 'Dayrūţ', null, 'Egypt', 'SNY', 'Africa/Cairo');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Wapolu Airport', 'Gandara', 'Porto', 'Portugal', 'WBC', 'Europe/Lisbon');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Botucatu - Tancredo de Almeida Neves Airport', 'Junín', null, 'Argentina', 'QCJ', 'America/Argentina/Buenos_Aires');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Sena Madureira Airport', 'Chifeng', null, 'China', 'ZMD', 'Asia/Shanghai');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Araçatuba Airport', 'Postřekov', null, 'Czech Republic', 'ARU', 'Europe/Berlin');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Lonely Air Station', 'Hongcheng', null, 'China', 'LNI', 'Asia/Chongqing');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Osmanabad Airport', 'Luodong', null, 'China', 'OMN', 'Asia/Shanghai');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Jabalpur Airport', 'Malaga', 'Andalucia', 'Spain', 'JLR', 'Europe/Madrid');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Capital City Airport', 'Concordia', null, 'Honduras', 'FFT', 'America/Tegucigalpa');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Sievierodonetsk Airport', 'Североморск-3', null, 'Russia', 'SEV', 'Europe/Moscow');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Kiwayu Airport', 'Lanpelan', null, 'Indonesia', 'KWY', 'Asia/Jakarta');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Nowra Airport', 'Hepu', null, 'China', 'NOA', 'Asia/Shanghai');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Whiting Field Naval Air Station - North', 'Zhangfang', null, 'China', 'NSE', 'Asia/Chongqing');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Pantnagar Airport', 'Zhosaly', null, 'Kazakhstan', 'PGH', 'Asia/Qyzylorda');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Dundas Airport', 'Chesma', null, 'Russia', 'DUN', 'Asia/Yekaterinburg');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Lusanga Airport', 'Dongming', null, 'China', 'LUS', 'Asia/Harbin');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Keshod Airport', 'Coxim', null, 'Brazil', 'IXK', 'America/Campo_Grande');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Shimojishima Airport', 'Mweka', null, 'Democratic Republic of the Congo', 'SHI', 'Africa/Lubumbashi');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Kokkola-Pietarsaari Airport', 'München', 'Bayern', 'Germany', 'KOK', 'Europe/Berlin');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Albert Lea Municipal Airport', 'Cibeureum', null, 'Indonesia', 'AEL', 'Asia/Jakarta');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Bulgan Airport', 'Mahaplag', null, 'Philippines', 'UGA', 'Asia/Manila');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Chatham Islands-Tuuta Airport', 'Kagay', null, 'Philippines', 'CHT', 'Asia/Manila');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Wangaratta Airport', 'Athlone', null, 'Ireland', 'WGT', 'Europe/Dublin');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Ralph C Weiser Field', 'Koungheul', null, 'Senegal', 'AGO', 'Africa/Banjul');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Shaw Air Force Base', 'Surulangun Rawas', null, 'Indonesia', 'SSC', 'Asia/Jakarta');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Chatham Seaplane Base', 'Kthella e Epërme', null, 'Albania', 'CYM', 'Europe/Tirane');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Janakpur Airport', 'Calangain', null, 'Philippines', 'JKR', 'Asia/Manila');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Ambohibary Airport', 'Karangsono', null, 'Indonesia', 'OHB', 'Asia/Jakarta');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Curuzu Cuatia Airport', 'Balyaga', null, 'Russia', 'UZU', 'Asia/Yakutsk');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Phanom Sarakham Airport', 'Bula', null, 'Philippines', 'PMM', 'Asia/Manila');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Sidney Municipal Airport', 'Zaolin', null, 'China', 'SXY', 'Asia/Chongqing');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('The O''Neill Municipal John L Baker Field', 'Lisiy Nos', null, 'Russia', 'ONL', 'Europe/Moscow');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Bulgan Airport', 'Lyubertsy', null, 'Russia', 'UGA', 'Europe/Moscow');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Lifuka Island Airport', 'Taganak', null, 'Philippines', 'HPA', 'Asia/Kuching');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Sabi Sabi Airport', 'San Cristóbal Verapaz', null, 'Guatemala', 'GSS', 'America/Guatemala');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Inkerman Airport', 'Alvito', 'Beja', 'Portugal', 'IKP', 'Europe/Lisbon');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Mahlon Sweet Field', 'Paniówki', null, 'Poland', 'EUG', 'Europe/Warsaw');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Reims-Champagne (BA 112) Air Base', 'Brezovica', null, 'Croatia', 'RHE', 'Europe/Zagreb');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('St. Lewis (Fox Harbour) Airport', 'Suqiaoxiang', null, 'China', 'YFX', 'Asia/Shanghai');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Sabu-Tardanu Airport', 'Morez', 'Franche-Comté', 'France', 'SAU', 'Europe/Zurich');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Tahsis Seaplane Base', 'Desē', null, 'Ethiopia', 'ZTS', 'Africa/Addis_Ababa');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Whakatane Airport', 'La Victoria', 'Veracruz Llave', 'Mexico', 'WHK', 'America/Mexico_City');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Wollogorang Airport', 'Napu', null, 'Indonesia', 'WLL', 'Asia/Makassar');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Lanai Airport', 'Xilian', null, 'China', 'LNY', 'Asia/Chongqing');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('St Clair County International Airport', 'Wangfu', null, 'China', 'PHN', 'Asia/Shanghai');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Cochstedt Airport', 'Santa Catalina', null, 'Peru', 'CSO', 'America/Lima');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Eurico de Aguiar Salles Airport', 'Rzeszów', null, 'Poland', 'VIX', 'Europe/Warsaw');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Hughes Airport', 'Viga', null, 'Philippines', 'HUS', 'Asia/Manila');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Fazenda das Represas Airport', 'Campos Belos', null, 'Brazil', '0', 'America/Sao_Paulo');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Jorge Newbery Airpark', 'Horad Smalyavichy', null, 'Belarus', 'AEP', 'Europe/Minsk');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('General Mariano Matamoros Airport', 'Kalmar', 'Kalmar', 'Sweden', 'CVJ', 'Europe/Stockholm');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Hechi Jinchengjiang Airport', 'União', null, 'Brazil', 'HCJ', 'America/Fortaleza');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Saarloq Heliport', 'Drahovo', null, 'Ukraine', 'QOQ', 'Europe/Uzhgorod');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Juan Mendoza Airport', 'Siguiri', null, 'Guinea', 'ORU', 'Africa/Conakry');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Astoria Regional Airport', 'Foluo', null, 'China', 'AST', 'Asia/Chongqing');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Bergen Airport Flesland', 'Al Bilād', null, 'Yemen', 'BGO', 'Asia/Aden');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Alexandria Homestead Airport', 'Sancha', null, 'China', 'AXL', 'Asia/Chongqing');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Kanainj Airport', 'Chuchkovo', null, 'Russia', 'KNE', 'Europe/Moscow');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Camp Page Airport (A-306)', 'El Calvario', 'Oaxaca', 'Mexico', 'QUN', 'America/Mexico_City');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Zhaotong Airport', 'Toulon', 'Provence-Alpes-Côte d''Azur', 'France', 'ZAT', 'Europe/Paris');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Jiri Airport', 'Sendangagung', null, 'Indonesia', 'JIR', 'Asia/Jakarta');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Chubu Centrair International Airport', 'Kuanheum', null, 'Indonesia', 'NGO', 'Asia/Makassar');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Manono Airport', 'Licun', null, 'China', 'MNO', 'Asia/Shanghai');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Pablo L. Sidar Airport', 'Bayḩān', null, 'Yemen', 'AZG', 'Asia/Aden');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Buchanan Field', 'Rano', null, 'Nigeria', 'CCR', 'Africa/Lagos');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Chuja Port Heliport', 'Kuala Lumpur', 'Kuala Lumpur', 'Malaysia', 'JCJ', 'Asia/Kuala_Lumpur');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Lenawee County Airport', 'Itajuípe', null, 'Brazil', 'ADG', 'America/Bahia');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Doha International Airport', 'Puerto Quellón', null, 'Chile', 'DIA', 'America/Santiago');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Carlos Rovirosa Pérez International Airport', 'Tomay Kichwa', null, 'Peru', 'VSA', 'America/Lima');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Southwest Florida International Airport', 'Norwalk', 'Connecticut', 'United States', 'RSW', 'America/New_York');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Barquisimeto International Airport', 'Várzea da Palma', null, 'Brazil', 'BRM', 'America/Sao_Paulo');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Diyawanna Oya Seaplane Base', 'Dulian', null, 'Philippines', 'DWO', 'Asia/Manila');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Khrabrovo Airport', 'Jindui', null, 'China', 'KGD', 'Asia/Chongqing');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Squamish Airport', 'Maae', null, 'Indonesia', 'YSE', 'Asia/Makassar');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Mount Gordon Airport', 'Kananga', null, 'Democratic Republic of the Congo', 'GPD', 'Africa/Lubumbashi');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Entebbe International Airport', 'Shenzhong', null, 'China', 'EBB', 'Asia/Chongqing');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Lawn Hill Airport', 'Miracema', null, 'Brazil', 'LWH', 'America/Sao_Paulo');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Nhon Co Airfield', 'Lhuentse', null, 'Bhutan', 'HOO', 'Asia/Kolkata');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Brigham City Regional Airport', 'San Jose', null, 'Philippines', 'BMC', 'Asia/Manila');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Manihiki Island Airport', 'Sankeng', null, 'China', 'MHX', 'Asia/Chongqing');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Malindi Airport', 'Rača', null, 'Serbia', 'MYD', 'Europe/Belgrade');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Yelizovo Airport', 'Butterworth', 'Pulau Pinang', 'Malaysia', 'PKC', 'Asia/Kuala_Lumpur');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Nanjing Lukou Airport', 'Strogino', null, 'Russia', 'NKG', 'Europe/Moscow');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Currillo Airport', 'Manhush', null, 'Ukraine', 'CUI', 'Europe/Zaporozhye');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Jomsom Airport', 'Tatabánya', 'Komárom-Esztergom', 'Hungary', 'JMO', 'Europe/Budapest');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Colonia Sarmiento Airport', 'Macon', 'Georgia', 'United States', 'OLN', 'America/New_York');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Talhar Airport', 'Vitanje', null, 'Slovenia', 'BDN', 'Europe/Ljubljana');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Guaporé Airport', 'Greensboro', 'North Carolina', 'United States', '0', 'America/New_York');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Lai Airport', 'Coroatá', null, 'Brazil', 'LTC', 'America/Fortaleza');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Mariscal Sucre International Airport', 'Tsaghkunk’', null, 'Armenia', 'UIO', 'Asia/Yerevan');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Gunnedah Airport', 'Detroit', 'Michigan', 'United States', 'GUH', 'America/Detroit');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Cable Airport', 'Xiaqiao', null, 'China', 'CCB', 'Asia/Chongqing');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Point Hope Airport', 'Cimuncang', null, 'Indonesia', 'PHO', 'Asia/Jakarta');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Barth Airport', 'Karanganyar', null, 'Indonesia', 'BBH', 'Asia/Jakarta');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Yampa Valley Airport', 'Strohonivka', null, 'Ukraine', 'HDN', 'Europe/Simferopol');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Morobe Airport', 'Tha Ruea', null, 'Thailand', 'OBM', 'Asia/Bangkok');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Amos/Magny Airport', 'Cullinan', null, 'South Africa', 'YEY', 'Africa/Johannesburg');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Tahoua Airport', 'Jiangwei', null, 'China', 'THZ', 'Asia/Shanghai');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('San Nicolas Airport', 'Postoloprty', null, 'Czech Republic', 'RIM', 'Europe/Prague');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Marmul Airport', 'Néa Smýrni', null, 'Greece', 'OMM', 'Europe/Athens');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Saravane Airport', 'Fucha', null, 'China', 'VNA', 'Asia/Chongqing');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Aragip Airport', 'Bastia', 'Corse', 'France', 'ARP', 'Europe/Paris');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Taranto-Grottaglie "Marcello Arlotta" Airport', 'Verkhniy Dashkesan', null, 'Azerbaijan', 'TAR', 'Asia/Baku');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Wilkes Barre Scranton International Airport', 'Hantsavichy', null, 'Belarus', 'AVP', 'Europe/Minsk');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Semera Airport', 'Mangli', null, 'Indonesia', 'SZE', 'Asia/Jakarta');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('São Gabriel da Cachoeira Airport', 'Dolod', null, 'China', 'SJL', 'Asia/Harbin');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Devils Lake Regional Airport', 'Erandique', null, 'Honduras', 'DVL', 'America/El_Salvador');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Craig Seaplane Base', 'Buang', null, 'Philippines', 'CGA', 'Asia/Manila');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Waynesville-St. Robert Regional Forney field', 'Lysá nad Labem', null, 'Czech Republic', 'TBN', 'Europe/Prague');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Rubem Berta Airport', 'Itabaiana', null, 'Brazil', 'URG', 'America/Fortaleza');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Alejandro Velasco Astete International Airport', 'Al Fashn', null, 'Egypt', 'CUZ', 'Africa/Cairo');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Chi Mei Airport', 'Bradenton', 'Florida', 'United States', 'CMJ', 'America/New_York');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Paris-Orly Airport', 'Little Rock', 'Arkansas', 'United States', 'ORY', 'America/Chicago');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Princess Juliana International Airport', 'Laozhuang', null, 'China', 'SXM', 'Asia/Chongqing');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Southend Airport', 'Xieba', null, 'China', 'SEN', 'Asia/Chongqing');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Hawkins Field', 'El Guapinol', null, 'Honduras', 'HKS', 'America/Tegucigalpa');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Masasi Airport', 'Rejasa Kaja', null, 'Indonesia', 'XMI', 'Asia/Makassar');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Mucuri Airport', 'Miatli', null, 'Russia', 'MVS', 'Europe/Moscow');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('São Lourenço Airport', 'Gachancipá', null, 'Colombia', 'SSO', 'America/Bogota');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Afyon Airport', 'Klakeh', null, 'Indonesia', 'AFY', 'Asia/Jakarta');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('La Baule-Escoublac Airport', 'Su-dong', null, 'South Korea', 'LBY', 'Asia/Seoul');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Borrego Valley Airport', 'Paris La Défense', 'Île-de-France', 'France', 'BXS', 'Europe/Paris');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Selfridge Air National Guard Base Airport', 'Tubarão', null, 'Brazil', 'MTC', 'America/Sao_Paulo');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Momeik Airport', 'Youguzhuang', null, 'China', 'MOE', 'Asia/Shanghai');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Ein Yahav Airfield', 'Baalbek', null, 'Lebanon', 'EIY', 'Asia/Beirut');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Dalnegorsk Airport', 'Yonghe', null, 'China', 'DHG', 'Asia/Shanghai');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Prince Abdulmohsin Bin Abdulaziz Airport', 'Hebeitun', null, 'China', 'YNB', 'Asia/Shanghai');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Gan International Airport', 'Kuusjoki', null, 'Finland', 'GAN', 'Europe/Helsinki');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Mougulu Airport', 'Okpoga', null, 'Nigeria', 'GUV', 'Africa/Lagos');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Great Falls International Airport', 'Wiang Nuea', null, 'Thailand', 'GTF', 'Asia/Bangkok');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Romeu Zema Airport', 'Quebradas', 'Lisboa', 'Portugal', 'AAX', 'Europe/Lisbon');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('General Pedro Jose Mendez International Airport', 'Bendo', null, 'Indonesia', 'CVM', 'Asia/Jakarta');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('RAF Odiham', 'Vaitogi', null, 'American Samoa', 'ODH', 'Pacific/Pago_Pago');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Khwahan Airport', 'Independencia', 'Nayarit', 'Mexico', 'KWH', 'America/Mazatlan');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Whitsunday Island Airport', 'Gaoyi', null, 'China', 'WSY', 'Asia/Shanghai');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Diapaga Airport', 'Anggana', null, 'Indonesia', 'DIP', 'Asia/Makassar');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('St Jean Airport', 'Ḩalabjah', null, 'Iraq', 'YJN', 'Asia/Baghdad');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Rankin Inlet Airport', 'Tangwāni', null, 'Pakistan', 'YRT', 'Asia/Karachi');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Mandalgobi Airport', 'Houmt Souk', null, 'Tunisia', 'MXW', 'Africa/Tunis');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Memmingen Allgau Airport', 'Al Maşdūr', null, 'Tunisia', 'FMM', 'Africa/Tunis');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Ivujivik Airport', 'Lourdes', null, 'Philippines', 'YIK', 'Asia/Manila');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Maimun Saleh Airport', 'Iralaya', null, 'Honduras', 'SBG', 'America/Managua');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Innamincka Airport', 'Auas', null, 'Honduras', 'INM', 'America/Tegucigalpa');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Reyes Murillo Airport', 'Doong', null, 'Philippines', 'NQU', 'Asia/Manila');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Tommy Kochon Airport', 'Weizhou', null, 'China', 'YCK', 'Asia/Shanghai');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Rokot Airport', 'Mirošov', null, 'Czech Republic', 'RKI', 'Europe/Prague');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Summit Airport', 'Sobral', null, 'Brazil', 'UMM', 'America/Fortaleza');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Tingwon Airport', 'Iperó', null, 'Brazil', 'TIG', 'America/Sao_Paulo');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Finley Airport', 'Dagohoy', null, 'Philippines', 'FLY', 'Asia/Manila');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Parry Sound Area Municipal Airport', 'Kristinehamn', 'Värmland', 'Sweden', 'YPD', 'Europe/Stockholm');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('St Paul Island Airport', 'Ciawitali', null, 'Indonesia', 'SNP', 'Asia/Jakarta');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Seychelles International Airport', 'Birendranagar', null, 'Nepal', 'SEZ', 'Asia/Kathmandu');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Jinchuan Airport', 'Kolodeznyy', null, 'Russia', 'JIC', 'Europe/Moscow');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Kauhajoki Airport', 'Yanglang', null, 'China', 'KHJ', 'Asia/Chongqing');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Churchill Falls Airport', 'Picos', null, 'Brazil', 'ZUM', 'America/Fortaleza');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Namtu Airport', 'Antopal’', null, 'Belarus', 'NMT', 'Europe/Minsk');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Penticton Airport', 'Sortavala', null, 'Russia', 'YYF', 'Europe/Moscow');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Dubrovnik Airport', 'Lecherías', null, 'Venezuela', 'DBV', 'America/Caracas');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Meyers Chuck Seaplane Base', 'San Diego', 'California', 'United States', 'WMK', 'America/Los_Angeles');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Chena Hot Springs Airport', 'Sigaboy', null, 'Philippines', 'CEX', 'Asia/Manila');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Bade Airport', 'Masipi West', null, 'Philippines', 'BXD', 'Asia/Manila');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Baie-Johan-Beetz Water Aerodrome', 'Kuala Terengganu', 'Terengganu', 'Malaysia', 'YBJ', 'Asia/Kuala_Lumpur');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Piedras Negras International Airport', 'Canis', null, 'Peru', 'PDS', 'America/Lima');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Ust-Tsylma Airport', 'Panambi', null, 'Brazil', 'UTS', 'America/Sao_Paulo');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Roi Et Airport', 'Shibirghān', null, 'Afghanistan', 'ROI', 'Asia/Kabul');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Düsseldorf Airport', 'Surin', null, 'Thailand', 'DUS', 'Asia/Bangkok');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Grand Strand Airport', 'Tibro', 'Västra Götaland', 'Sweden', 'CRE', 'Europe/Stockholm');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Tilin Airport', 'Delcevo', null, 'Macedonia', 'TIO', 'Europe/Skopje');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Childress Municipal Airport', 'Jiyang', null, 'China', 'CDS', 'Asia/Shanghai');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Magas Airport', 'Waerana', null, 'Indonesia', 'IGT', 'Asia/Makassar');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Southport Airport', 'Riosucio', null, 'Colombia', 'SHQ', 'America/Bogota');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Scribner State Airport', 'Al Bahlūlīyah', null, 'Syria', 'SCB', 'Asia/Damascus');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Jwaneng Airport', 'Mbalmayo', null, 'Cameroon', 'JWA', 'Africa/Douala');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Tres Esquinas Air Base', 'Cisiec', null, 'Poland', 'TQS', 'Europe/Warsaw');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Iokea Airport', 'Magalalag', null, 'Philippines', 'IOK', 'Asia/Manila');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Bandar Abbas International Airport', 'Deqing', null, 'China', 'BND', 'Asia/Shanghai');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Martin State Airport', 'El Rincón', null, 'Panama', 'MTN', 'America/Panama');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Ogden Hinckley Airport', 'Yingde’er', null, 'China', 'OGD', 'Asia/Chongqing');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('San Salvador de Paul Airport', 'Berezanka', null, 'Ukraine', 'SVV', 'Europe/Simferopol');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Chanute Martin Johnson Airport', 'Nazareth', null, 'Israel', 'CNU', 'Asia/Jerusalem');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Cold Bay Airport', 'Yuzhno-Sukhokumsk', null, 'Russia', 'CDB', 'Europe/Moscow');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Isla Mujeres Airport', 'Äänekoski', null, 'Finland', 'ISJ', 'Europe/Helsinki');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('West 30th St. Heliport', 'Cikadondongdesa', null, 'Indonesia', 'JRA', 'Asia/Jakarta');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Bosaso Airport', 'Sasebo', null, 'Japan', 'BSA', 'Asia/Tokyo');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Fort Smith Airport', 'Desa Borogojol', null, 'Indonesia', 'YSM', 'Asia/Jakarta');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Lee Gilmer Memorial Airport', 'Al Qadmūs', null, 'Syria', 'GVL', 'Asia/Damascus');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Keisah Airport', 'Yenangyaung', null, 'Myanmar', 'KEA', 'Asia/Rangoon');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Dos Lagunas Airport', 'Yaring', null, 'Thailand', 'DON', 'Asia/Bangkok');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Friedman Memorial Airport', 'Kristianstad', 'Skåne', 'Sweden', 'SUN', 'Europe/Stockholm');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Goondiwindi Airport', 'Miami', 'Florida', 'United States', 'GOO', 'America/New_York');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Berbera Airport', 'Jeberos', null, 'Peru', 'BBO', 'America/Lima');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Antonio Narino Airport', 'Shangyi', null, 'China', 'PSO', 'Asia/Chongqing');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Gu-Lian Airport', 'Gaoleshan', null, 'China', 'OHE', 'Asia/Chongqing');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Alberto Lleras Camargo Airport', 'Kudang', null, 'Indonesia', 'SOX', 'Asia/Jakarta');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Tabiteuea North Airport', 'Lushikeng', null, 'China', 'TBF', 'Asia/Shanghai');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Nervino Airport', 'Kovdor', null, 'Russia', 'NVN', 'Europe/Moscow');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Nissan Island Airport', 'Guri i Zi', null, 'Albania', 'IIS', 'Europe/Tirane');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Belluno Airport', 'Sułoszowa', null, 'Poland', 'BLX', 'Europe/Warsaw');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Bergen Airport Flesland', 'Soasio', null, 'Indonesia', 'BGO', 'Asia/Jayapura');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Salerno Landing Zone Airport', 'Tuymazy', null, 'Russia', 'OLR', 'Asia/Yekaterinburg');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Redcliffe Airport', 'Biito', null, 'Indonesia', 'RCL', 'Asia/Makassar');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Desroches Airport', 'Kosonsoy Shahri', null, 'Uzbekistan', 'DES', 'Asia/Tashkent');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Panguitch Municipal Airport', 'Owode', null, 'Nigeria', 'PNU', 'Africa/Lagos');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Willow Airport', 'Rio Verde de Mato Grosso', null, 'Brazil', 'WOW', 'America/Campo_Grande');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Savannah Hilton Head International Airport', 'Baumata', null, 'Indonesia', 'SAV', 'Asia/Makassar');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Lime Acres Finsch Mine Airport', 'Pimian', null, 'China', 'LMR', 'Asia/Chongqing');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Bonnechere Airport', 'Shangping', null, 'China', 'YXI', 'Asia/Shanghai');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Villa Gesell Airport', 'Abucayan', null, 'Philippines', 'VLG', 'Asia/Manila');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Dahl Creek Airport', 'Shezhu', null, 'China', 'DCK', 'Asia/Shanghai');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Lusikisiki Airport', 'Xinglong', null, 'China', 'LUJ', 'Asia/Harbin');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Okhotsk Airport', 'Nanortalik', null, 'Greenland', 'OHO', 'America/Godthab');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Limbang Airport', 'Salzburg', 'Salzburg', 'Austria', 'LMN', 'Europe/Vienna');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Fukuoka Airport', 'Caozhen', null, 'China', 'FUK', 'Asia/Chongqing');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Kitkatla Seaplane Base', 'Balidian', null, 'China', 'YKK', 'Asia/Shanghai');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Wright Field', 'Kagawasan', null, 'Philippines', 'DWF', 'Asia/Manila');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Kornasoren Airfield', 'Kuruman', null, 'South Africa', 'FOO', 'Africa/Johannesburg');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Pocono Mountains Municipal Airport', 'Masis', null, 'Armenia', 'MPO', 'Asia/Yerevan');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Taree Airport', 'Białobrzegi', null, 'Poland', 'TRO', 'Europe/Warsaw');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Gothenburg-Landvetter Airport', 'Panganiban', null, 'Philippines', 'GOT', 'Asia/Manila');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Palo Verde Airport', 'Bedford', 'Québec', 'Canada', 'SRL', 'America/Montreal');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Tweed New Haven Airport', 'Oemollo', null, 'Indonesia', 'HVN', 'Asia/Makassar');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Gaua Island Airport', 'Bagorejo', null, 'Indonesia', 'ZGU', 'Asia/Jakarta');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Omega Airport', 'Qiankou', null, 'China', 'OMG', 'Asia/Shanghai');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Bodaybo Airport', 'Shangping', null, 'China', 'ODO', 'Asia/Shanghai');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Phoenix Deer Valley Airport', 'Pule', null, 'Indonesia', 'DVT', 'Asia/Jakarta');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('City of Derry Airport', 'Hyesan-si', null, 'North Korea', 'LDY', 'Asia/Pyongyang');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Buckeye Municipal Airport', 'Fengshan', null, 'China', 'BXK', 'Asia/Shanghai');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Santa Monica Municipal Airport', 'Duyun', null, 'China', 'SMO', 'Asia/Chongqing');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Usinsk Airport', 'Huaribamba', null, 'Peru', 'USK', 'America/Lima');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Lake Macquarie Airport', 'Lavradio', 'Setúbal', 'Portugal', 'BEO', 'Europe/Lisbon');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Mbandaka Airport', 'Lesogorsk', null, 'Russia', 'MDK', 'Asia/Irkutsk');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Telida Airport', 'Yekaterinovka', null, 'Russia', 'TLF', 'Asia/Vladivostok');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Béchar Boudghene Ben Ali Lotfi Airport', 'Himensulan', null, 'Philippines', 'CBH', 'Asia/Manila');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Gävle Sandviken Airport', 'Wyszogród', null, 'Poland', 'GVX', 'Europe/Warsaw');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Bojnord Airport', 'Al Ḩarf', null, 'Yemen', 'BJB', 'Asia/Aden');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Ignatyevo Airport', 'Jiangwan', null, 'China', 'BQS', 'Asia/Chongqing');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Kahramanmaraş Airport', 'Budapest', 'Budapest', 'Hungary', 'KCM', 'Europe/Budapest');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Alpine Airstrip', 'Xirikxiy', null, 'China', 'DQH', 'Asia/Urumqi');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Hat Yai International Airport', 'Zhuangke', null, 'China', 'HDY', 'Asia/Shanghai');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('East 34th Street Heliport', 'Entebbe', null, 'Uganda', 'TSS', 'Africa/Kampala');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Beletwene Airport', 'Laramate', null, 'Peru', 'BLW', 'America/Lima');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Andøya Airport', 'Shādegān', null, 'Iran', 'ANX', 'Asia/Tehran');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Rutland Plains Airport', 'Roissy Charles-de-Gaulle', 'Île-de-France', 'France', 'RTP', 'Europe/Paris');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Hachijojima Airport', 'Dongling', null, 'China', 'HAC', 'Asia/Shanghai');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Atizapan De Zaragoza Airport', 'Xuefeng', null, 'China', 'AZP', 'Asia/Shanghai');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Torrejón Airport', 'Fuzhou', null, 'China', 'TOJ', 'Asia/Shanghai');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Lopez Island Airport', 'Anambongan', null, 'Philippines', 'LPS', 'Asia/Manila');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Mukah Airport', 'Aqtoghay', null, 'Kazakhstan', 'MKM', 'Asia/Almaty');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Douglas Lake Airport', 'Messina', 'Sicilia', 'Italy', 'DGF', 'Europe/Rome');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Page Field', 'Kafr ad Dīk', null, 'Palestinian Territory', 'FMY', 'Asia/Jerusalem');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Kneeland Airport', 'Seabra', null, 'Brazil', 'NLN', 'America/Bahia');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Laurence G Hanscom Field', 'Puqi', null, 'China', 'BED', 'Asia/Shanghai');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Oram Airport', 'Niandui', null, 'China', 'RAX', 'Asia/Urumqi');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Chino Airport', 'Otavalo', null, 'Ecuador', 'CNO', 'America/Guayaquil');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Kursk East Airport', 'Doong', null, 'Philippines', 'URS', 'Asia/Manila');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Fua''amotu International Airport', 'Candelaria', null, 'Colombia', 'TBU', 'America/Bogota');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Elrose Airport', 'Bobigny', 'Île-de-France', 'France', 'ERQ', 'Europe/Paris');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Córdoba Airport', 'Bedford', 'Québec', 'Canada', 'ODB', 'America/Montreal');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Ogoki Post Airport', 'Minas de Marcona', null, 'Peru', 'YOG', 'America/Lima');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Puerto Rico Airport', 'Julun', null, 'China', 'PCC', 'Asia/Chongqing');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Kushiro Airport', 'Magdug', null, 'Philippines', 'KUH', 'Asia/Manila');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Kirkland Lake Airport', 'Shuangyuan', null, 'China', 'YKX', 'Asia/Chongqing');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Mekoryuk Airport', 'Simitli', null, 'Bulgaria', 'MYU', 'Europe/Sofia');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Siwea Airport', 'El Zapote', 'Guerrero', 'Mexico', 'SWE', 'America/Mexico_City');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Rose Bay Seaplane Base', 'Montepuez', null, 'Mozambique', 'RSE', 'Africa/Maputo');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Spencer Municipal Airport', 'Promna', null, 'Poland', 'SPW', 'Europe/Warsaw');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Gray Army Air Field', 'Nanyuan', null, 'China', 'GRF', 'Asia/Shanghai');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Zhytomyr Airport', 'Babah Rot', null, 'Indonesia', 'ZTR', 'Asia/Pontianak');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Pine Bluff Regional Airport, Grider Field', 'Puubheto', null, 'Indonesia', 'PBF', 'Asia/Makassar');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Glengyle Airport', 'Nyzhni Sirohozy', null, 'Ukraine', 'GLG', 'Europe/Zaporozhye');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Romeu Zema Airport', 'Tanahwulan', null, 'Indonesia', 'AAX', 'Asia/Jakarta');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Hill Air Force Base', 'Bengga', null, 'Indonesia', 'HIF', 'Asia/Makassar');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Nordholz Naval Airbase', 'Lansing', 'Michigan', 'United States', 'FCN', 'America/Detroit');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Black Hills Airport-Clyde Ice Field', 'Zelenoborskiy', null, 'Russia', 'SPF', 'Europe/Moscow');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Arso Airport', 'Portariá', null, 'Greece', 'ARJ', 'Europe/Athens');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Campbell River Seaplane Base', 'Singasari', null, 'Indonesia', 'YHH', 'Asia/Jakarta');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Vilhelmina Airport', 'Kamigyō-ku', null, 'Japan', 'VHM', 'Asia/Tokyo');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Pobedilovo Airport', 'Solina', null, 'Bosnia and Herzegovina', 'KVX', 'Europe/Sarajevo');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Chevak Airport', 'Santa Eulália', 'Braga', 'Portugal', 'VAK', 'Europe/Lisbon');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Bahia Cupica Airport', 'Santa Rosa', 'Nuevo Leon', 'Mexico', 'BHF', 'America/Monterrey');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Bumbar Airport', 'San Isidro', null, 'Philippines', 'BMB', 'Asia/Manila');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Waca Airport', 'Anápolis', null, 'Brazil', 'WAC', 'America/Sao_Paulo');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Cascais Airport', 'Wang Noi', null, 'Thailand', 'CAT', 'Asia/Bangkok');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('McKellar-Sipes Regional Airport', 'Ōmiya', null, 'Japan', 'MKL', 'Asia/Tokyo');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('RAF Fairford', 'Wonda', null, 'Indonesia', 'FFD', 'Asia/Makassar');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Trabzon International Airport', 'Néa Karváli', null, 'Greece', 'TZX', 'Europe/Athens');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Achutupo Airport', 'San Jose', null, 'Philippines', 'ACU', 'Asia/Manila');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Yemelyanovo Airport', 'Nidri', null, 'Greece', 'KJA', 'Europe/Athens');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Coronel E Carvajal Airport', 'Gävle', 'Gävleborg', 'Sweden', 'XMS', 'Europe/Stockholm');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Nancy-Essey Airport', 'Upper Hell''s Gate', null, 'Bonaire, Saint Eustatius and Saba ', 'ENC', 'America/Lower_Princes');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Eurico de Aguiar Salles Airport', 'Bangkalan', null, 'Indonesia', 'VIX', 'Asia/Makassar');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Jurado Airport', 'Trunovskoye', null, 'Russia', 'JUO', 'Europe/Moscow');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Rivers Airport', 'Strängnäs', 'Södermanland', 'Sweden', 'YYI', 'Europe/Stockholm');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Schönhagen Airport', 'Pingdingshan', null, 'China', 'QXH', 'Asia/Chongqing');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Gustavo Rizo Airport', 'Odemira', 'Beja', 'Portugal', 'BCA', 'Europe/Lisbon');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('King Abdulaziz Air Base', 'Beiping', null, 'China', 'DHA', 'Asia/Chongqing');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('St. Anthony Airport', 'Yejia', null, 'China', 'YAY', 'Asia/Shanghai');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Albert Lea Municipal Airport', 'Maxu', null, 'China', 'AEL', 'Asia/Chongqing');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Barreiras Airport', 'Guruyan', null, 'Philippines', 'BRA', 'Asia/Manila');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Naukati Bay Seaplane Base', 'Semikarakorsk', null, 'Russia', 'NKI', 'Europe/Moscow');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Chigorodó Airport', 'Watuka', null, 'Indonesia', 'IGO', 'Asia/Makassar');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Campo do Meio Airport', 'Ziguinchor', null, 'Senegal', '0', 'Africa/Dakar');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Kurwina Airport', 'Amizmiz', null, 'Morocco', 'KWV', 'Africa/Casablanca');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Nanjing Lukou Airport', 'San Pedro Pinula', null, 'Guatemala', 'NKG', 'America/Guatemala');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Nanping Wuyishan Airport', 'Prigi', null, 'Indonesia', 'WUS', 'Asia/Jakarta');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Ralph M Calhoun Memorial Airport', 'Guling', null, 'China', 'TAL', 'Asia/Shanghai');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Vilyuisk Airport', 'Sundsvall', 'Västernorrland', 'Sweden', 'VYI', 'Europe/Stockholm');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Analalava Airport', 'Arnaía', null, 'Greece', 'HVA', 'Europe/Athens');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Henderson Executive Airport', 'Fucun', null, 'China', 'HSH', 'Asia/Shanghai');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Arthur N Neu Airport', 'Höganäs', 'Skåne', 'Sweden', 'CIN', 'Europe/Copenhagen');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Deniliquin Airport', 'Seka', null, 'Thailand', 'DNQ', 'Asia/Bangkok');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('William R Fairchild International Airport', 'Osias', null, 'Philippines', 'CLM', 'Asia/Manila');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Merville-Calonne Airport', 'Uchaly', null, 'Russia', 'HZB', 'Asia/Yekaterinburg');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Île d''Yeu Airport', 'Lokuuy', null, 'Indonesia', 'IDY', 'Asia/Makassar');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Hopetoun Airport', 'Kanlagay', null, 'Philippines', 'HTU', 'Asia/Manila');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Hammerfest Airport', 'Caigangan', null, 'Philippines', 'HFT', 'Asia/Manila');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Lubang Airport', 'Xijiao', null, 'China', 'LBX', 'Asia/Chongqing');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Siem Reap International Airport', 'Hoani', null, 'Comoros', 'REP', 'Indian/Comoro');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Yuba County Airport', 'Dong’an', null, 'China', 'MYV', 'Asia/Harbin');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Maiana Airport', 'Maroua', null, 'Cameroon', 'MNK', 'Africa/Douala');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Rurutu Airport', 'Sidirókastro', null, 'Greece', 'RUR', 'Europe/Athens');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Kenosha Regional Airport', 'Jinja', null, 'Uganda', 'ENW', 'Africa/Kampala');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Tiko Airport', 'Charlottenberg', 'Värmland', 'Sweden', 'TKC', 'Europe/Oslo');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Ye Airport', 'Londres', null, 'Argentina', 'XYE', 'America/Argentina/La_Rioja');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Berz-Macomb Airport', 'Aroroy', null, 'Philippines', 'UIZ', 'Asia/Manila');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Lauro Carneiro de Loyola Airport', 'Krujë', null, 'Albania', 'JOI', 'Europe/Tirane');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Wokal Field Glasgow International Airport', 'Pilang', null, 'Indonesia', 'GGW', 'Asia/Jakarta');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Mt. Fuji Shizuoka Airport', 'Shikhazany', null, 'Russia', 'FSZ', 'Europe/Moscow');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Akwa Ibom International Airport', 'Varpaisjärvi', null, 'Finland', 'QUO', 'Europe/Helsinki');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Tambohorano Airport', 'Hamhŭng', null, 'North Korea', 'WTA', 'Asia/Pyongyang');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Tambao Airport', 'Katav-Ivanovsk', null, 'Russia', 'TMQ', 'Asia/Yekaterinburg');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Greater Moncton International Airport', 'Xinxikou', null, 'China', 'YQM', 'Asia/Shanghai');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Layang-Layang Airport', 'Qarqīn', null, 'Afghanistan', 'LAC', 'Asia/Kabul');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Kashechewan Airport', 'Memphis', 'Tennessee', 'United States', 'ZKE', 'America/Chicago');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Kemmerer Municipal Airport', 'Rū-ye Sang', null, 'Afghanistan', 'EMM', 'Asia/Kabul');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Craig Moffat Airport', 'Néa Karváli', null, 'Greece', 'CIG', 'Europe/Athens');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Decatur County Industrial Air Park', 'Columbia', 'Missouri', 'United States', 'BGE', 'America/Chicago');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Cahors-Lalbenque Airport', 'Alcorriol', 'Santarém', 'Portugal', 'ZAO', 'Europe/Lisbon');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Cochrane Airport', 'Oliveirinha', 'Viseu', 'Portugal', 'YCN', 'Europe/Lisbon');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Niue International Airport', 'Huangqiao', null, 'China', 'IUE', 'Asia/Shanghai');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Juancho E. Yrausquin Airport', 'Magdalena', null, 'Peru', 'SAB', 'America/Lima');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Okmulgee Regional Airport', 'Heichengzi', null, 'China', 'OKM', 'Asia/Harbin');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Talkeetna Airport', 'Kabalo', null, 'Democratic Republic of the Congo', 'TKA', 'Africa/Lubumbashi');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Ulan-Ude Airport (Mukhino)', 'Morshansk', null, 'Russia', 'UUD', 'Europe/Moscow');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Camiri Airport', 'Loučeň', null, 'Czech Republic', 'CAM', 'Europe/Prague');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Renner Field-Goodland Municipal Airport', 'Kuala Tuha', null, 'Indonesia', 'GLD', 'Asia/Pontianak');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Pärnu Airport', 'Burevestnik', null, 'Russia', 'EPU', 'Europe/Moscow');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Robertson Airport', 'Spodnja Hajdina', null, 'Slovenia', 'ROD', 'Europe/Ljubljana');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('General Santos International Airport', 'Tarczyn', null, 'Poland', 'GES', 'Europe/Warsaw');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Naval Air Station Key West/Boca Chica Field', 'Nueva Fuerza', null, 'Philippines', 'NQX', 'Asia/Manila');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Fujairah International Airport', 'Kobayashi', null, 'Japan', 'FJR', 'Asia/Tokyo');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Austin Airport', 'Malinta', null, 'Philippines', 'ASQ', 'Asia/Manila');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Tainan Airport', 'Tsimkavichy', null, 'Belarus', 'TNN', 'Europe/Minsk');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Bradley International Airport', 'Tucheng', null, 'China', 'BDL', 'Asia/Chongqing');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Fairmont Hot Springs Airport', 'Kedungdoro', null, 'Indonesia', 'YCZ', 'Asia/Jakarta');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Learmonth Airport', 'Rincón', null, 'Dominican Republic', 'LEA', 'America/Santo_Domingo');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Gladstone Airport', 'Waiwejak', null, 'Indonesia', 'GLT', 'Asia/Makassar');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Gurupi Airport', 'Nýřany', null, 'Czech Republic', 'GRP', 'Europe/Prague');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Erzurum International Airport', 'Santo Niño', null, 'Philippines', 'ERZ', 'Asia/Manila');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Bagram Air Base', 'Garunggang', null, 'Indonesia', 'OAI', 'Asia/Jakarta');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Irkutsk Airport', 'Qacha’s Nek', null, 'Lesotho', 'IKT', 'Africa/Maseru');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Moro Airport', 'Songkan', null, 'China', 'MXH', 'Asia/Chongqing');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Kotabangun Airport', 'Komga', null, 'South Africa', 'KOD', 'Africa/Johannesburg');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Soyo Airport', 'Massaguet', null, 'Chad', 'SZA', 'Africa/Ndjamena');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Brive Souillac Airport', 'Lescar', 'Aquitaine', 'France', 'BVE', 'Europe/Paris');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Corumbá International Airport', 'Neikeng', null, 'China', 'CMG', 'Asia/Shanghai');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Ogoki Post Airport', 'Orda', null, 'Russia', 'YOG', 'Asia/Yekaterinburg');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Long Xuyên Airport', 'Balangpule', null, 'Indonesia', 'XLO', 'Asia/Jakarta');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Sultan Ismail Petra Airport', 'Fukura', null, 'Japan', 'KBR', 'Asia/Tokyo');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Libo Airport', 'Biny Selo', null, 'Azerbaijan', 'LLB', 'Asia/Baku');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Gävle Sandviken Airport', 'Korsze', null, 'Poland', 'GVX', 'Europe/Warsaw');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Vermilion Regional Airport', 'Pisan', null, 'Indonesia', 'DNV', 'Asia/Makassar');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Simanggang Airport', 'San Antonio', 'Guerrero', 'Mexico', 'SGG', 'America/Mexico_City');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Ronald Reagan Washington National Airport', 'Namp’o', null, 'North Korea', 'DCA', 'Asia/Pyongyang');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('O R Tambo International', 'Dob', null, 'Slovenia', 'JNB', 'Europe/Ljubljana');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Tozeur Nefta International Airport', 'Karlstad', 'Värmland', 'Sweden', 'TOE', 'Europe/Stockholm');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Birdsville Airport', 'Baoping', null, 'China', 'BVI', 'Asia/Chongqing');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Chitral Airport', 'Brades', null, 'Montserrat', 'CJL', 'America/Montserrat');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Boulder City Municipal Airport', 'Oslo', 'Oslo', 'Norway', 'BLD', 'Europe/Oslo');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Amasya Merzifon Airport', 'Krajan', null, 'Indonesia', 'MZH', 'Asia/Jakarta');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Bahia Cupica Airport', 'Yangtan', null, 'China', 'BHF', 'Asia/Shanghai');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Røros Airport', 'Dongxing', null, 'China', 'RRS', 'Asia/Harbin');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Sungai Tiang Airport', 'Argir', null, 'Faroe Islands', 'SXT', 'Atlantic/Faroe');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Crested Butte Airpark', 'Columbus', 'Ohio', 'United States', 'CSE', 'America/New_York');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Erume Airport', 'Maopingchang', null, 'China', 'ERU', 'Asia/Chongqing');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Hillside Airport', 'Yulao', null, 'China', 'HLL', 'Asia/Chongqing');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Kota Kinabalu International Airport', 'Rizal', null, 'Philippines', 'BKI', 'Asia/Manila');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Matagami Airport', 'Essen', 'Nordrhein-Westfalen', 'Germany', 'YNM', 'Europe/Berlin');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Mogilev Airport', 'Junqueiro', 'Lisboa', 'Portugal', 'MVQ', 'Europe/Lisbon');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Montgomery-Gibbs Executive Airport', 'Berlin', 'Berlin', 'Germany', 'MYF', 'Europe/Berlin');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Allegheny County Airport', 'Wutun', null, 'China', 'AGC', 'Asia/Chongqing');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Dillingham Airfield', 'Petauke', null, 'Zambia', 'HDH', 'Africa/Lusaka');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Manakara Airport', 'Negla', null, 'Indonesia', 'WVK', 'Asia/Jakarta');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Uşak Airport', 'Ichnya', null, 'Ukraine', 'USQ', 'Europe/Kiev');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Oiapoque Airport', 'Chodzież', null, 'Poland', 'OYK', 'Europe/Warsaw');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Ikela Airport', 'Ratenggoji', null, 'Indonesia', 'IKL', 'Asia/Makassar');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Nunapitchuk Airport', 'Richards Bay', null, 'South Africa', 'NUP', 'Africa/Johannesburg');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Yakushima Airport', 'Kushtia', null, 'Bangladesh', 'KUM', 'Asia/Dhaka');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Turkmenabat Airport', 'Kuala Lumpur', 'Kuala Lumpur', 'Malaysia', 'CRZ', 'Asia/Kuala_Lumpur');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Aek Godang Airport', 'Malekān', null, 'Iran', 'AEG', 'Asia/Tehran');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Zhengzhou Xinzheng International Airport', 'Pingshui', null, 'China', 'CGO', 'Asia/Shanghai');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Matari Airport', 'Solomenskoye', null, 'Russia', 'IRP', 'Europe/Moscow');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Semporna Airport', 'Kugluktuk', 'Nunavut', 'Canada', 'SMM', 'America/Yellowknife');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Lambarene Airport', 'Huata', null, 'Peru', 'LBQ', 'America/Lima');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Bundi Airport', 'Nāḩiyat Hīrān', null, 'Iraq', 'BNT', 'Asia/Baghdad');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Lester B. Pearson International Airport', 'Mimbaan Timur', null, 'Indonesia', 'YYZ', 'Asia/Jakarta');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Turaif Domestic Airport', 'Riga', null, 'Latvia', 'TUI', 'Europe/Riga');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Kangerlussuaq Airport', 'Sannikovo', null, 'Russia', 'SFJ', 'Asia/Omsk');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Denver International Airport', 'Vila Franca da Beira', 'Coimbra', 'Portugal', 'DEN', 'Europe/Lisbon');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Berbérati Airport', 'Granadero Baigorria', null, 'Argentina', 'BBT', 'America/Argentina/Cordoba');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Salisbury Ocean City Wicomico Regional Airport', 'Mangli', null, 'Indonesia', 'SBY', 'Asia/Jakarta');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Grand Central Airport', 'Jastrzębia Góra', null, 'Poland', 'GCJ', 'Europe/Warsaw');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Ulusaba Airport', 'Ponyri Vtoryye', null, 'Russia', 'ULX', 'Europe/Moscow');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Megève Airport', 'Kota Bharu', 'Kelantan', 'Malaysia', 'MVV', 'Asia/Kuala_Lumpur');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Benito Salas Airport', 'Novopodrezkovo', null, 'Russia', 'NVA', 'Europe/Moscow');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Paris-Orly Airport', 'Decatur', 'Georgia', 'United States', 'ORY', 'America/New_York');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Baco Airport', 'Leran Kulon', null, 'Indonesia', 'BCO', 'Asia/Jakarta');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Eneabba Airport', 'Babica', null, 'Poland', 'ENB', 'Europe/Warsaw');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Dresden Airport', 'Tomas', null, 'Peru', 'DRS', 'America/Lima');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Sloulin Field International Airport', 'Nong Ruea', null, 'Thailand', 'ISN', 'Asia/Bangkok');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Alferez FAP Alfredo Vladimir Sara Bauer Airport', 'Wonosari', null, 'Indonesia', 'AOP', 'Asia/Jakarta');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Port Said Airport', 'Couva', null, 'Trinidad and Tobago', 'PSD', 'America/Port_of_Spain');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('East Midlands Airport', 'Shiyang', null, 'China', 'EMA', 'Asia/Shanghai');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('El Tepual Airport', 'Las Matas de Farfán', null, 'Dominican Republic', 'PMC', 'America/Santo_Domingo');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Great Falls International Airport', 'Kaustinen', null, 'Finland', 'GTF', 'Europe/Helsinki');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Chipinge Airport', 'Dahe', null, 'China', 'CHJ', 'Asia/Shanghai');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Taitung Airport', 'Alegre', null, 'Brazil', 'TTT', 'America/Sao_Paulo');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Kirkwall Airport', 'Ovruch', null, 'Ukraine', 'KOI', 'Europe/Kiev');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Imonda Airport', 'Shiraoka', null, 'Japan', 'IMD', 'Asia/Tokyo');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Ellison Onizuka Kona International At Keahole Airport', 'Ongi', null, 'Mongolia', 'KOA', 'Asia/Ulaanbaatar');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Tefé Airport', 'Jiuhua', null, 'China', 'TFF', 'Asia/Shanghai');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Presidente José Sarney Airport', 'Nandasmo', null, 'Nicaragua', 'PDR', 'America/Managua');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Moose Lake Airport', 'Lesuhe', null, 'China', 'YAD', 'Asia/Chongqing');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Chachapoyas Airport', 'São Pedro Gafanhoeira', 'Évora', 'Portugal', 'CHH', 'Europe/Lisbon');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Ine Airport', 'Tall Tamr', null, 'Syria', 'IMI', 'Europe/Istanbul');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Marshall Memorial Municipal Airport', 'Albuquerque', 'New Mexico', 'United States', 'MHL', 'America/Denver');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Taguatinga Airport', 'Yangyuan', null, 'China', 'QHN', 'Asia/Shanghai');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('La Abraq Airport', 'Yuqian', null, 'China', 'LAQ', 'Asia/Shanghai');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Pajala Airport', 'Tambaksari', null, 'Indonesia', 'PJA', 'Asia/Jakarta');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Santa Teresita Airport', 'Veliko Tŭrnovo', null, 'Bulgaria', 'SST', 'Europe/Sofia');
insert into Airport-Mockaroo (name, city, region, country, iata_code, timezone) values ('Sparta Fort Mc Coy Airport', 'Przytyk', null, 'Poland', 'CMY', 'Europe/Warsaw');
